# -*- mode: python ; coding: utf-8 -*-
import os

a = Analysis(
    ['app.py'],
    pathex=[os.path.dirname(os.path.abspath(SPEC))],
    binaries=[],
    datas=[
        ('Pictures', 'Pictures'), 
        ('dark.qss', '.'), 
        ('girly.qss', '.'),
        ('Pictures/Logo.ico', '.'),
        ('Pictures/Logo.png', '.')
    ],
    hiddenimports=[
        'PySide6.QtSvg',
        'PySide6.QtGui',
        'PySide6.QtCore',
        'PySide6.QtWidgets',
        'docxtpl',
        'jinja2',
        'pandas',
        'openpyxl',
        'qrcode',
        'PIL',
        'numpy',
        'core',
        'core.logic',
        'core.logging',
        'core.utils',
        'gui',
        'gui.constants',
        'gui.models',
        'gui.workers',
        'gui.main_window',
        'gui.mixins',
        'gui.mixins.app_shell_mixin',
        'gui.mixins.appearance_mixin',
        'gui.mixins.bilder_vorschau_mixin',
        'gui.mixins.categories_mixin',
        'gui.mixins.generation_mixin',
        'gui.mixins.log_view_mixin',
        'gui.mixins.main_controls_mixin',
        'gui.mixins.media_sizes_mixin',
        'gui.mixins.pdf_export_mixin',
        'gui.mixins.project_mixin',
        'gui.mixins.signage_rules_mixin',
        'gui.mixins.templates_mixin',
        'app',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='DocxTpl_Automatisierung_v7.0',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='Pictures/Logo.ico',
)
